# [An introduction to Numpy and Scipy](http://www.engr.ucsb.edu/~shell/che210d/numpy.pdf)

In [2]:
import numpy as np

## Arrays

Arrays are similar to lists in Python, except that every element of an array must be of the same type,

In [27]:
a = np.array([1,4,5,8], float)
print(a)
print(type(a))

[ 1.  4.  5.  8.]
<class 'numpy.ndarray'>


In [35]:
b = [1, 4, 5, '8']
b

[1, 4, 5, '8']

In [37]:
c = np.array([1, 4, 5, '8'])
c

array(['1', '4', '5', '8'], 
      dtype='<U21')

In [32]:
print(a[:2])
print(a[3])
a[0] = 5.
print(a)

[ 1.  4.]
8.0
[ 5.  4.  5.  8.]


In [43]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)
print(a[0,0])
print(a[0,1])

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
1.0
2.0


In [45]:
print(a[1,:])
print(a[:,2])
print(a.shape)
print(a.dtype)

[ 4.  5.  6.]
[ 3.  6.]
(2, 3)
float64


In [47]:
print(len(a))
print(2 in a)
print(4 in a)
print(0 in a)

2
True
True
False


In [48]:
a = np.array(range(10), float)
print(a)
a = a.reshape((5,2))
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]]


Keep in mind that Python's name-binding approach still applies to arrays. The copy function can be used to create a new, separate copy of an array in memory if needed:

In [50]:
a = np.array([1, 2, 3], float)
b = a
c = a.copy()
a[0] = 0
print(a)
print(b)
print(c)

[ 0.  2.  3.]
[ 0.  2.  3.]
[ 1.  2.  3.]


In [53]:
print(a.tolist())
print(list(a))
s = a.tostring()
print(s)
print(np.fromstring(s))

[0.0, 2.0, 3.0]
[0.0, 2.0, 3.0]
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'
[ 0.  2.  3.]


In [54]:
a.fill(0)
print(a)

[ 0.  0.  0.]


In [58]:
a = np.array(range(6)).reshape((2, 3))
print(a)
b = a.transpose()
print(b)
c = a.flatten()
print(c)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[0 1 2 3 4 5]


In [60]:
a = np.array([1,2],float)
b = np.array([3,4,5,6],float)
c = np.array([7,8,9],float)
print(np.concatenate((a, b, c)))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [63]:
a = np.array([[1,2], [3, 4]], float)
b = np.array([[5,6], [7, 8]], float)
print(np.concatenate((a, b)))
print(np.concatenate((a, b), axis = 1))

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]
[[ 1.  2.  5.  6.]
 [ 3.  4.  7.  8.]]


 the dimensionality of an array can be increased using the newaxis constant in bracket

In [70]:
a = np.array([1, 2, 3], float)
print(a)
print(a.shape)
print(a[:, np.newaxis])
print(a[:, np.newaxis].shape)
print(a[np.newaxis, :])
print(a[np.newaxis, :].shape)

[ 1.  2.  3.]
(3,)
[[ 1.]
 [ 2.]
 [ 3.]]
(3, 1)
[[ 1.  2.  3.]]
(1, 3)


## Other ways to create arrays

`arange` function is similar to the `range` function but returns an array

In [74]:
print(np.arange(5, dtype = float))
print(np.arange(1, 6, 2, dtype = int))

[ 0.  1.  2.  3.  4.]
[1 3 5]


In [75]:
print(np.ones((2, 3), dtype = float))
print(np.zeros(7, dtype = int))

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[0 0 0 0 0 0 0]


The `zeros_like` and `ones_like` functions create a new array with the same dimensions and type of an existing one

In [77]:
a = np.array(range(6)).reshape(2, 3)
print(a)
print(np.ones_like(a))
print(np.zeros_like(a))

[[0 1 2]
 [3 4 5]]
[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


In [79]:
print(np.identity(4, dtype=float))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


The `eye` function returns matrices with ones along the kth diagonal

In [81]:
print(np.eye(4, k=1,dtype=float))
print(np.eye(4, k=2,dtype=float))

[[ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]]
[[ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


## Array mathemataics

When standard mathematical operations are used with arrays, they are applied on an element- by-element basis

In [84]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
print(a + b)
print(a - b)
print(a * b)
print(b / a)
print(a % b)
print(b**a)

[ 6.  4.  9.]
[-4.  0. -3.]
[  5.   4.  18.]
[ 5.  1.  2.]
[ 1.  0.  3.]
[   5.    4.  216.]


For two-dimensional arrays, multiplication remains elementwise and does not correspond to matrix multiplication

In [87]:
a = np.array([[1,2], [3,4]], float)
b = np.array([[2,0], [1,3]], float)
print(a * b)

[[  2.   0.]
 [  3.  12.]]


In [88]:
a = np.array([1,2,3],float)
b = np.array([4,5],float)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [89]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

arrays that do not match in the number of dimensions will be broadcasted by Python to perform mathematical operations

In [91]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
a + b

array([[ 0.,  5.],
       [ 2.,  7.],
       [ 4.,  9.]])

In [94]:
a = np.zeros((2, 2), float)
b = np.array([-1, 3], float)
print(a + b)
print(a + b[np.newaxis,:])
print(a + b[:,np.newaxis])

[[-1.  3.]
 [-1.  3.]]
[[-1.  3.]
 [-1.  3.]]
[[-1. -1.]
 [ 3.  3.]]


In [97]:
a = np.array([1.21, 4.84, 9.61], float)
print(np.sqrt(a))
print(np.floor(a))
print(np.rint(a)) # rounded integer

[ 1.1  2.2  3.1]
[ 1.  4.  9.]
[  1.   5.  10.]


In [98]:
print(np.pi)
print(np.e)

3.141592653589793
2.718281828459045


## Array iteration

In [99]:
a = np.array([1, 4, 5], float)
for x in a:
    print(x)

1.0
4.0
5.0


In [102]:
a = np.array([[1,2], [3,4], [5,6]], float)
for x in a:
    print(x)
for (x, y) in a:
    print(x*y)

[ 1.  2.]
[ 3.  4.]
[ 5.  6.]
2.0
12.0
30.0


## Basic array operations

In [108]:
a = np.array([2, 4, 3], float)
print(a.sum())
print(sum(a))
print(np.sum(a))

print(a.prod())
#print(prod(a)) # error
print(np.prod(a))

print(a.mean())
print(np.mean(a))
print(a.var())
print(np.var(a))
print(a.std())
print(np.std(a))
print(a.min())
print(np.min(a))
print(a.max())
print(np.max(a))
print(a.argmin())
print(np.argmin(a))
print(a.argmax())
print(np.argmax(a))

9.0
9.0
9.0
24.0
24.0
3.0
3.0
0.666666666667
0.666666666667
0.816496580928
0.816496580928
2.0
2.0
4.0
4.0
0
0
1
1


axis: average 할 방향. shape에서 날려버릴 차원의 index

In [114]:
a = np.array([[0,2], [3,-1], [3,5]], float)
print(a.shape)
print(a.mean(axis = 0))
print(a.mean(axis = 1))

a = np.array([[[0,2], [3,-1], [3,5]], [[1,3], [4,0], [4,6]]], float)
print(a.shape)
print(a.mean(axis = 0))
print(a.mean(axis = 1))
print(a.mean(axis = 2))

(3, 2)
[ 2.  2.]
[ 1.  1.  4.]
(2, 3, 2)
[[ 0.5  2.5]
 [ 3.5 -0.5]
 [ 3.5  5.5]]
[[ 2.  2.]
 [ 3.  3.]]
[[ 1.  1.  4.]
 [ 2.  2.  5.]]


In [117]:
a = np.array([6,2,5,-1,0], float)
print(sorted(a))
a.sort()
print(a)

[-1.0, 0.0, 2.0, 5.0, 6.0]
[-1.  0.  2.  5.  6.]


In [119]:
a = np.array([6, 5, 4, -1, 0], float)
print(a.clip(0, 5))
print(np.clip(a, 0, 5))

[ 5.  5.  4.  0.  0.]
[ 5.  5.  4.  0.  0.]


In [120]:
a = np.array([1, 1, 4, 5, 5, 5, 7], float)
print(np.unique(a))
# print(a.unique()) # error

[ 1.  4.  5.  7.]


In [122]:
a = np.array([[1, 2], [3, 4]], float)
print(a.diagonal())
print(np.diagonal(a))
print(np.diag(a))

[ 1.  4.]
[ 1.  4.]
[ 1.  4.]


## Comparison operations and value testing

In [4]:
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)
print(a > b)
print(a == b)
print(a <= b)


[ True False False]
[False  True False]
[False  True  True]


In [5]:
a > 2

array([False,  True, False], dtype=bool)

In [7]:
c = np.array([True, False, False], bool)
print(any(c))
print(all(c))

True
False


In [16]:
a = np.array([1, 3, 0], float)
print(np.logical_and(a > 0, a <3))
b = np.array([True, False, True], bool)
print(np.logical_not(b))
c = np.array([False, True, False], bool)
print(np.logical_or(b, c))
print(b | c)
print(b & c)

[ True False False]
[False  True False]
[ True  True  True]
[ True  True  True]
[False False False]


In [18]:
a = np.array([1, 3, 0], float)
print(np.where(a != 0, 1 / a, a))
print(np.where(a > 0, 3, 2))

[ 1.          0.33333333  0.        ]
[3 3 2]


/usr/local/lib/python3.5/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in true_divide
  from ipykernel import kernelapp as app


In [22]:
a = np.array([[0, 1], [3, 0]], float)
print(a.nonzero())
a = np.array([[0, 3, 2], [1, 2, 5]], float)
print(a.nonzero())
a = np.array([[0, 0, 2], [0, 0, 0]], float)
print(a.nonzero())

(array([0, 1]), array([1, 0]))
(array([0, 0, 1, 1, 1]), array([1, 2, 0, 1, 2]))
(array([0]), array([2]))


In [24]:
a = np.array([1, np.NaN, np.Inf], float)
print(a)
print(np.isnan(a))
print(np.isinf(a))

[  1.  nan  inf]
[False  True False]
[False False  True]


## Array item selection and manipulation

In [20]:
a = np.array([[6,4], [5,9]], float)
print(a >= 6)
print(a[a>=6])
print(a[np.array([[True, False], [False, False]])])

a[np.logical_and(a > 5, a < 9)]

[[ True False]
 [False  True]]
[ 6.  9.]
[ 6.]


array([ 6.])

In [31]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
print(a[b])
print(a.take(b))

[ 2.  2.  4.  8.  6.  4.]
[ 2.  2.  4.  8.  6.  4.]


In [29]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
print(a[b, c])
print(a[c, :])
print(a[c])
print(a[:, c])


[  1.   4.  16.  16.   4.]
[[ 1.  1.  4.  4.  1.]
 [ 1.  4.  4.  4.  4.]]
[[  1.   4.]
 [  9.  16.]
 [  9.  16.]
 [  9.  16.]
 [  9.  16.]]
[[  1.   4.]
 [  9.  16.]
 [  9.  16.]
 [  9.  16.]
 [  9.  16.]]
[[  1.   4.   4.   4.   4.]
 [  9.  16.  16.  16.  16.]]


In [34]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([0,0,1], int)
print(a.take(b, axis=0))
print(a[b, :])
print(a.take(b, axis=1))
print(a[:, b])

[[ 0.  1.]
 [ 0.  1.]
 [ 2.  3.]]
[[ 0.  1.]
 [ 0.  1.]
 [ 2.  3.]]
[[ 0.  0.  1.]
 [ 2.  2.  3.]]
[[ 0.  0.  1.]
 [ 2.  2.  3.]]


In [36]:
a = np.array([0, 1, 2, 3, 4, 5], float)
b = np.array([9, 8, 7], float)
a.put([0, 3], b)
print(a)
a[0] = 0
print(a)

[ 9.  1.  2.  8.  4.  5.]
[ 0.  1.  2.  8.  4.  5.]


In [37]:
a = np.array([0, 1, 2, 3, 4, 5], float)
a.put([0, 3], 5)
a

array([ 5.,  1.,  2.,  5.,  4.,  5.])

## Vector and matrix mathematics

The dot function also generalizes to matrix multiplication

In [38]:
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
print(a.dot(b))
print(np.dot(a, b))

5.0
5.0


In [43]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)
print(np.dot(a, b))
print(np.dot(b, a)) # b 는 행 벡터?
print(np.dot(a, c))
print(np.dot(c, a))

[  3.  13.]
[  6.  11.]
[[  4.   0.]
 [ 14.   2.]]
[[ 2.  4.]
 [ 0.  4.]]


It is also possible to generate inner, outer, and cross products of matrices and vectors. For vectors, note that the inner product is equivalent to the dot product

In [45]:
a = np.array([1, 4, 0], float)
b = np.array([2, 2, 1], float)
print(np.outer(a, b))
print(np.inner(a, b))
print(np.cross(a, b))

[[ 2.  2.  1.]
 [ 8.  8.  4.]
 [ 0.  0.  0.]]
10.0
[ 4. -1. -6.]


NumPy also comes with a number of built-in routines for linear algebra calculations.  
These can be found in the sub-module linalg. Among these are routines for dealing with matrices and their inverses.

In [55]:
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], float)
print(a)
print(np.linalg.det(a))

[[ 4.  2.  0.]
 [ 9.  3.  7.]
 [ 1.  2.  1.]]
-48.0


In [48]:
vals, vecs = np.linalg.eig(a)
print(vals)
print(vecs)

[ 8.85591316  1.9391628  -2.79507597]
[[-0.3663565  -0.54736745  0.25928158]
 [-0.88949768  0.5640176  -0.88091903]
 [-0.27308752  0.61828231  0.39592263]]


In [56]:
b = np.linalg.inv(a)
print(b)
print(np.dot(a, b))

[[ 0.22916667  0.04166667 -0.29166667]
 [ 0.04166667 -0.08333333  0.58333333]
 [-0.3125      0.125       0.125     ]]
[[  1.00000000e+00   5.55111512e-17   0.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   2.22044605e-16]
 [  0.00000000e+00   1.38777878e-17   1.00000000e+00]]


In [57]:
a = np.array([[1, 3, 4], [5, 2,3]], float)
U, s, Vh = np.linalg.svd(a)
print(U)
print(s)
print(Vh)

[[-0.6113829  -0.79133492]
 [-0.79133492  0.6113829 ]]
[ 7.46791327  2.86884495]
[[-0.61169129 -0.45753324 -0.64536587]
 [ 0.78971838 -0.40129005 -0.46401635]
 [-0.046676   -0.79349205  0.60678804]]


## Polynomial mathematics

NumPy supplies methods for working with polynomials. Given a set of roots, it is possible to show the polynomial coefficients

In [61]:
print(np.poly([-1, 1, 1, 10]))
print(np.poly([0, -2]))

[  1. -11.   9.  11. -10.]
[ 1.  2.  0.]


The opposite operation can be performed: given a set of coefficients, the root function returns all of the polynomial roots

In [62]:
print(np.roots([1, 4, -2, 3]))
print(np.roots([1, -4, 4]))

[-4.57974010+0.j          0.28987005+0.75566815j  0.28987005-0.75566815j]
[ 2.  2.]


미분(derivatives)과 적분(integrating)

In [63]:
np.polyint([1, 1, 1, 1])

array([ 0.25      ,  0.33333333,  0.5       ,  1.        ,  0.        ])

In [64]:
np.polyder([1, 4, 4])

array([2, 4])

In [65]:
np.polyval([1, -2, 0, 2], 4)

34

polyadd, polysub, polymul, polydiv 함수들도 있다.

fit polynomial of specified order. (with least-squares). 뭐야. 이거

In [66]:
x = [1, 2, 3, 4, 5, 6, 7, 8]
y = [0, 2, 1, 3, 7, 10, 11, 19]
np.polyfit(x, y, 2)

array([ 0.375     , -0.88690476,  1.05357143])

## Statistics

In [68]:
a = np.array([1, 4, 3, 8, 9, 2, 3], float)
print(np.median(a))

3.0


In [98]:
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float)
c = np.corrcoef(a)
print(c)
print(np.cov(a))


[[ 1.          0.72870505]
 [ 0.72870505  1.        ]]
[[ 0.91666667  2.08333333]
 [ 2.08333333  8.91666667]]


In [109]:

print((np.mean(a[0]*a[1]) - np.mean(a[0]) * np.mean(a[1])) / np.std(a[0]) / np.std(a[1]))

0.728705046661


## Random numbers

In [117]:
np.random.seed(293423)
np.random.rand(5)

array([ 0.33677247,  0.52693437,  0.79529578,  0.78867702,  0.02147624])

In [118]:
print(np.random.rand(2, 3))

[[ 0.84612516  0.0704939   0.1526965 ]
 [ 0.77831701  0.80821151  0.82198398]]


In [119]:
np.random.random() # [0.0, 1.0)

0.9023965286127028

In [131]:
np.random.randint(5, 10) # [min, max)

8

In [132]:
np.random.poisson(6.0) # from descrete poisson distribution. mu = 6.0

5

In [133]:
np.random.normal(1.5, 4.0) # from normal distribution. mu = 1.5, sigma = 4.0. default mu = 0.0, sigma = 1.0

-2.543701623074049

In [137]:
print(np.random.normal(size = 5))
print(np.random.poisson(size = 4))

[ 0.76870525 -0.73315898 -0.63316684  0.66661769 -0.51928963]
[2 2 1 0]


In [139]:
l = np.arange(10)
print(l)
np.random.shuffle(l)
print(l)

[0 1 2 3 4 5 6 7 8 9]
[8 7 0 5 9 4 3 6 1 2]


----

## Other functions to know about

## Modules available in SciPy